In [ ]:
import numpy as np
import pandas as pd

## Рабочий код для 2 измерений

In [ ]:
a1 = pd.read_table('G:для юпитера/053/a1.RV1', sep='     ', header=None)
a2 = pd.read_table('G:для юпитера/053/a2.RV2', sep='     ', header=None)
b1 = pd.read_table('G:для юпитера/053/b1.RV1', sep='     ', header=None)
b2 = pd.read_table('G:для юпитера/053/b2.RV2', sep='     ', header=None)
c1 = pd.read_table('G:для юпитера/053/c1.RV1', sep='     ', header=None)
c2 = pd.read_table('G:для юпитера/053/c2.RV2', sep='     ', header=None)

a1.dropna(axis=0, inplace=True)
a1.rename(columns={0 : 'time' , 1 : 'volt'}, inplace=True)
a1['time'] = a1['time'].astype(float)
maxa1 = a1[a1['volt'] == a1['volt'].max()]
umaxa1 = maxa1[maxa1['time'] == maxa1['time'].max()].reset_index().drop(['index'], axis=1).T.reset_index().\
rename(columns={'index': 'time', 0: 'volt'}).T.rename(columns={0:'tmax', 1: 'vmax'})
tna1 = a1.loc[a1['time']<=11].max().reset_index().rename(columns={'index': 'time' , 0 : 'volt'}).\
T.rename(columns={0 : 'tn', 1 : 'vn'})
t100a1 = a1.query('95 < time < 101')
ut100a1 = t100a1[t100a1['time'] == t100a1['time'].max()].T
ut100a1.columns=['100']
t200a1 = a1.query('195 < time < 201')
ut200a1 = t200a1[t200a1['time'] == t200a1['time'].max()].T
ut200a1.columns=['200']
t360a1 = a1.query('355 < time < 361')
ut360a1 = t360a1[t360a1['time'] == t360a1['time'].max()].T
ut360a1.columns=['360']
t500a1 = a1.query('495 < time < 501')
ut500a1 = t500a1[t500a1['time'] == t500a1['time'].max()].T
ut500a1.columns=['500']
t600a1 = a1.query('595 < time < 601')
ut600a1 = t600a1[t600a1['time'] == t600a1['time'].max()].T
ut600a1.columns=['600']
t720a1 = a1.query('715 < time < 721')
ut720a1 = t720a1[t720a1['time'] == t720a1['time'].max()].T
ut720a1.columns=['720']
t900a1 = a1.query('895 < time < 901')
ut900a1 = t900a1[t900a1['time'] == t900a1['time'].max()].T
ut900a1.columns=['900']
t1080a1 = a1.query('1075 < time < 1081')
ut1080a1 = t1080a1[t1080a1['time'] == t1080a1['time'].max()].T
ut1080a1.columns=['1080']
t1200a1 = a1.query('1195 < time < 1201')
ut1200a1 = t1200a1[t1200a1['time'] == t1200a1['time'].max()].T
ut1200a1.columns=['1200']
t1300a1 = a1.query('1295 < time < 1301')
ut1300a1 = t1300a1[t1300a1['time'] == t1300a1['time'].max()].T
ut1300a1.columns=['1300']
t1440a1 = a1.query('1435 < time < 1441')
ut1440a1 = t1440a1[t1440a1['time'] == t1440a1['time'].max()].T
ut1440a1.columns=['1440']
t1600a1 = a1.query('1595 < time < 1601')
ut1600a1 = t1600a1[t1600a1['time'] == t1600a1['time'].max()].T
ut1600a1.columns=['1600']
t1700a1 = a1.query('1695 < time < 1701')
ut1700a1 = t1700a1[t1700a1['time'] == t1700a1['time'].max()].T
ut1700a1.columns=['1700']
tmina1 = a1.query('1795 < time < 1801')
utmina1 = tmina1[tmina1['time'] == tmina1['time'].max()].T
utmina1.columns=['min']
cdsa1 = pd.concat([tna1, umaxa1, ut100a1, ut200a1, ut360a1, ut500a1, ut600a1, ut720a1, ut900a1, ut1080a1, ut1200a1, ut1300a1, 
                 ut1440a1, ut1600a1, ut1700a1, utmina1],axis=1, join='inner')

a2.dropna(axis=0, inplace=True)
a2.rename(columns={0 : 'time' ,  1 : 'volt'}, inplace=True)
a2['time'] = a2['time'].astype(float)
maxa2 = a2[a2['volt'] == a2['volt'].max()]
umaxa2 = maxa2[maxa2['time'] == maxa2['time'].max()].reset_index().drop(['index'], axis=1).T.reset_index().\
rename(columns={'index': 'time', 0: 'volt'}).T.rename(columns={0:'tmax', 1: 'vmax'})
tna2 = a2.loc[a2['time']<=11].max().reset_index().rename(columns={'index': 'time' , 0 : 'volt'}).\
T.rename(columns={0 : 'tn', 1 : 'vn'})
t100a2 = a2.query('95 < time < 101')
ut100a2 = t100a2[t100a2['time'] == t100a2['time'].max()].T
ut100a2.columns=['100']
t200a2 = a2.query('195 < time < 201')
ut200a2 = t200a2[t200a2['time'] == t200a2['time'].max()].T
ut200a2.columns=['200']
t360a2 = a2.query('355 < time < 361')
ut360a2 = t360a2[t360a2['time'] == t360a2['time'].max()].T
ut360a2.columns=['360']
t500a2 = a2.query('495 < time < 501')
ut500a2 = t500a2[t500a2['time'] == t500a2['time'].max()].T
ut500a2.columns=['500']
t600a2 = a2.query('595 < time < 601')
ut600a2 = t600a2[t600a2['time'] == t600a2['time'].max()].T
ut600a2.columns=['600']
t720a2 = a2.query('715 < time < 721')
ut720a2 = t720a2[t720a2['time'] == t720a2['time'].max()].T
ut720a2.columns=['720']
t900a2 = a2.query('895 < time < 901')
ut900a2 = t900a2[t900a2['time'] == t900a2['time'].max()].T
ut900a2.columns=['900']
t1080a2 = a2.query('1075 < time < 1081')
ut1080a2 = t1080a2[t1080a2['time'] == t1080a2['time'].max()].T
ut1080a2.columns=['1080']
t1200a2 = a2.query('1195 < time < 1201')
ut1200a2 = t1200a2[t1200a2['time'] == t1200a2['time'].max()].T
ut1200a2.columns=['1200']
t1300a2 = a2.query('1295 < time < 1301')
ut1300a2 = t1300a2[t1300a2['time'] == t1300a2['time'].max()].T
ut1300a2.columns=['1300']
t1440a2 = a2.query('1435 < time < 1441')
ut1440a2 = t1440a2[t1440a2['time'] == t1440a2['time'].max()].T
ut1440a2.columns=['1440']
t1600a2 = a2.query('1595 < time < 1601')
ut1600a2 = t1600a2[t1600a2['time'] == t1600a2['time'].max()].T
ut1600a2.columns=['1600']
t1700a2 = a2.query('1695 < time < 1701')
ut1700a2 = t1700a2[t1700a2['time'] == t1700a2['time'].max()].T
ut1700a2.columns=['1700']
tmina2 = a2.query('1795 < time < 1801')
utmina2 = tmina2[tmina2['time'] == tmina2['time'].max()].T
utmina2.columns=['min']
cdsa2 = pd.concat([tna2, umaxa2, ut100a2, ut200a2, ut360a2, ut500a2, ut600a2, ut720a2, ut900a2, ut1080a2, ut1200a2, ut1300a2,
                   ut1440a2, ut1600a2, ut1700a2, utmina2],axis = 1,join='inner')

b1.dropna(axis=0, inplace=True)
b1.rename(columns={0 : 'time' ,  1 : 'volt'}, inplace=True)
b1['time'] = b1['time'].astype(float)
maxb1 = b1[b1['volt'] == b1['volt'].max()]
umaxb1 = maxb1[maxb1['time'] == maxb1['time'].max()].reset_index().drop(['index'], axis=1).T.reset_index().\
rename(columns={'index': 'time', 0: 'volt'}).T.rename(columns={0:'tmax', 1: 'vmax'})
tnb1 = b1.loc[b1['time']<=11].max().reset_index().rename(columns={'index': 'time' , 0 : 'volt'}).\
T.rename(columns={0 : 'tn', 1 : 'vn'})
t100b1 = b1.query('95 < time < 101')
ut100b1 = t100b1[t100b1['time'] == t100b1['time'].max()].T
ut100b1.columns=['100']
t200b1 = b1.query('195 < time < 201')
ut200b1 = t200b1[t200b1['time'] == t200b1['time'].max()].T
ut200b1.columns=['200']
t360b1 = b1.query('355 < time < 361')
ut360b1 = t360b1[t360b1['time'] == t360b1['time'].max()].T
ut360b1.columns=['360']
t500b1 = b1.query('495 < time < 501')
ut500b1 = t500b1[t500b1['time'] == t500b1['time'].max()].T
ut500b1.columns=['500']
t600b1 = b1.query('595 < time < 601')
ut600b1 = t600b1[t600b1['time'] == t600b1['time'].max()].T
ut600b1.columns=['600']
t720b1 = b1.query('715 < time < 721')
ut720b1 = t720b1[t720b1['time'] == t720b1['time'].max()].T
ut720b1.columns=['720']
t900b1 = b1.query('895 < time < 901')
ut900b1 = t900b1[t900b1['time'] == t900b1['time'].max()].T
ut900b1.columns=['900']
t1080b1 = b1.query('1075 < time < 1081')
ut1080b1 = t1080b1[t1080b1['time'] == t1080b1['time'].max()].T
ut1080b1.columns=['1080']
t1200b1 = b1.query('1195 < time < 1201')
ut1200b1 = t1200b1[t1200b1['time'] == t1200b1['time'].max()].T
ut1200b1.columns=['1200']
t1300b1 = b1.query('1295 < time < 1301')
ut1300b1 = t1300b1[t1300b1['time'] == t1300b1['time'].max()].T
ut1300b1.columns=['1300']
t1440b1 = b1.query('1435 < time < 1441')
ut1440b1 = t1440b1[t1440b1['time'] == t1440b1['time'].max()].T
ut1440b1.columns=['1440']
t1600b1 = b1.query('1595 < time < 1601')
ut1600b1 = t1600b1[t1600b1['time'] == t1600b1['time'].max()].T
ut1600b1.columns=['1600']
t1700b1 = b1.query('1695 < time < 1701')
ut1700b1 = t1700b1[t1700b1['time'] == t1700b1['time'].max()].T
ut1700b1.columns=['1700']
tminb1 = b1.query('1795 < time < 1801')
utminb1 = tminb1[tminb1['time'] == tminb1['time'].max()].T
utminb1.columns=['min']
cdsb1 = pd.concat([tnb1, umaxb1, ut100b1, ut200b1, ut360b1, ut500b1, ut600b1, ut720b1, ut900b1, ut1080b1, ut1200b1, ut1300b1,
                   ut1440b1, ut1600b1, ut1700b1, utminb1],axis = 1,join='inner')

b2.dropna(axis=0, inplace=True)
b2.rename(columns={0 : 'time' ,  1 : 'volt'}, inplace=True)
b2['time'] = b2['time'].astype(float)
maxb2 = b2[b2['volt'] == b2['volt'].max()]
umaxb2 = maxb2[maxb2['time'] == maxb2['time'].max()].reset_index().drop(['index'], axis=1).T.reset_index().\
rename(columns={'index': 'time', 0: 'volt'}).T.rename(columns={0:'tmax', 1: 'vmax'})
tnb2 = b2.loc[b2['time']<=11].max().reset_index().rename(columns={'index': 'time' , 0 : 'volt'}).\
T.rename(columns={0 : 'tn', 1 : 'vn'})
t100b2 = b2.query('95 < time < 101')
ut100b2 = t100b2[t100b2['time'] == t100b2['time'].max()].T
ut100b2.columns=['100']
t200b2 = b2.query('195 < time < 201')
ut200b2 = t200b2[t200b2['time'] == t200b2['time'].max()].T
ut200b2.columns=['200']
t360b2 = b2.query('355 < time < 361')
ut360b2 = t360b2[t360b2['time'] == t360b2['time'].max()].T
ut360b2.columns=['360']
t500b2 = b2.query('495 < time < 501')
ut500b2 = t500b2[t500b2['time'] == t500b2['time'].max()].T
ut500b2.columns=['500']
t600b2 = b2.query('595 < time < 601')
ut600b2 = t600b2[t600b2['time'] == t600b2['time'].max()].T
ut600b2.columns=['600']
t720b2 = b2.query('715 < time < 721')
ut720b2 = t720b2[t720b2['time'] == t720b2['time'].max()].T
ut720b2.columns=['720']
t900b2 = b2.query('895 < time < 901')
ut900b2 = t900b2[t900b2['time'] == t900b2['time'].max()].T
ut900b2.columns=['900']
t1080b2 = b2.query('1075 < time < 1081')
ut1080b2 = t1080b2[t1080b2['time'] == t1080b2['time'].max()].T
ut1080b2.columns=['1080']
t1200b2 = b2.query('1195 < time < 1201')
ut1200b2 = t1200b2[t1200b2['time'] == t1200b2['time'].max()].T
ut1200b2.columns=['1200']
t1300b2 = b2.query('1295 < time < 1301')
ut1300b2 = t1300b2[t1300b2['time'] == t1300b2['time'].max()].T
ut1300b2.columns=['1300']
t1440b2 = b2.query('1435 < time < 1441')
ut1440b2 = t1440b2[t1440b2['time'] == t1440b2['time'].max()].T
ut1440b2.columns=['1440']
t1600b2 = b2.query('1595 < time < 1601')
ut1600b2 = t1600b2[t1600b2['time'] == t1600b2['time'].max()].T
ut1600b2.columns=['1600']
t1700b2 = b2.query('1695 < time < 1701')
ut1700b2 = t1700b2[t1700b2['time'] == t1700b2['time'].max()].T
ut1700b2.columns=['1700']
tminb2 = b2.query('1795 < time < 1801')
utminb2 = tminb2[tminb2['time'] == tminb2['time'].max()].T
utminb2.columns=['min']
cdsb2 = pd.concat([tnb2, umaxb2, ut100b2, ut200b2, ut360b2, ut500b2, ut600b2, ut720b2, ut900b2, ut1080b2, ut1200b2, ut1300b2,
                   ut1440b2, ut1600b2, ut1700b2, utminb2],axis = 1,join='inner')

c1.dropna(axis=0, inplace=True)
c1.rename(columns={0 : 'time', 1 : 'volt'}, inplace=True)
c1['time'] = c1['time'].astype(float)
maxc1 = c1[c1['volt'] == c1['volt'].max()]
umaxc1 = maxc1[maxc1['time'] == maxc1['time'].max()].reset_index().drop(['index'], axis=1).T.reset_index().\
rename(columns={'index': 'time', 0: 'volt'}).T.rename(columns={0:'tmax', 1: 'vmax'})
tnc1 = c1.loc[c1['time']<=11].max().reset_index().rename(columns={'index': 'time' , 0 : 'volt'}).\
T.rename(columns={0 : 'tn', 1 : 'vn'})
t100c1 = c1.query('95 < time < 101')
ut100c1 = t100c1[t100c1['time'] == t100c1['time'].max()].T
ut100c1.columns=['100']
t200c1 = c1.query('195 < time < 201')
ut200c1 = t200c1[t200c1['time'] == t200c1['time'].max()].T
ut200c1.columns=['200']
t360c1 = c1.query('355 < time < 361')
ut360c1 = t360c1[t360c1['time'] == t360c1['time'].max()].T
ut360c1.columns=['360']
t500c1 = c1.query('495 < time < 501')
ut500c1 = t500c1[t500c1['time'] == t500c1['time'].max()].T
ut500c1.columns=['500']
t600c1 = c1.query('595 < time < 601')
ut600c1 = t600c1[t600c1['time'] == t600c1['time'].max()].T
ut600c1.columns=['600']
t720c1 = c1.query('715 < time < 721')
ut720c1 = t720c1[t720c1['time'] == t720c1['time'].max()].T
ut720c1.columns=['720']
t900c1 = c1.query('895 < time < 901')
ut900c1 = t900c1[t900c1['time'] == t900c1['time'].max()].T
ut900c1.columns=['900']
t1080c1 = c1.query('1075 < time < 1081')
ut1080c1 = t1080c1[t1080c1['time'] == t1080c1['time'].max()].T
ut1080c1.columns=['1080']
t1200c1 = c1.query('1195 < time < 1201')
ut1200c1 = t1200c1[t1200c1['time'] == t1200c1['time'].max()].T
ut1200c1.columns=['1200']
t1300c1 = c1.query('1295 < time < 1301')
ut1300c1 = t1300c1[t1300c1['time'] == t1300c1['time'].max()].T
ut1300c1.columns=['1300']
t1440c1 = c1.query('1435 < time < 1441')
ut1440c1 = t1440c1[t1440c1['time'] == t1440c1['time'].max()].T
ut1440c1.columns=['1440']
t1600c1 = c1.query('1595 < time < 1601')
ut1600c1 = t1600c1[t1600c1['time'] == t1600c1['time'].max()].T
ut1600c1.columns=['1600']
t1700c1 = c1.query('1695 < time < 1701')
ut1700c1 = t1700c1[t1700c1['time'] == t1700c1['time'].max()].T
ut1700c1.columns=['1700']
tminc1 = c1.query('1795 < time < 1801')
utminc1 = tminc1[tminc1['time'] == tminc1['time'].max()].T
utminc1.columns=['min']
cdsc1 = pd.concat([tnc1, umaxc1, ut100c1, ut200c1, ut360c1, ut500c1, ut600c1, ut720c1, ut900c1, ut1080c1, ut1200c1, ut1300c1,
                   ut1440c1, ut1600c1, ut1700c1, utminc1],axis = 1,join='inner')

c2.dropna(axis=0, inplace=True)
c2.rename(columns={0 : 'time', 1 : 'volt'}, inplace=True)
c2['time'] = c2['time'].astype(float)
maxc2 = c2[c2['volt'] == c2['volt'].max()]
umaxc2 = maxc2[maxc2['time'] == maxc2['time'].max()].reset_index().drop(['index'], axis=1).T.reset_index().\
rename(columns={'index': 'time', 0: 'volt'}).T.rename(columns={0:'tmax', 1: 'vmax'})
tnc2 = c2.loc[c2['time']<=11].max().reset_index().rename(columns={'index': 'time' , 0 : 'volt'}).\
T.rename(columns={0 : 'tn', 1 : 'vn'})
t100c2 = c2.query('95 < time < 101')
ut100c2 = t100c2[t100c2['time'] == t100c2['time'].max()].T
ut100c2.columns=['100']
t200c2 = c2.query('195 < time < 201')
ut200c2 = t200c2[t200c2['time'] == t200c2['time'].max()].T
ut200c2.columns=['200']
t360c2 = c2.query('355 < time < 361')
ut360c2 = t360c2[t360c2['time'] == t360c2['time'].max()].T
ut360c2.columns=['360']
t500c2 = c2.query('495 < time < 501')
ut500c2 = t500c2[t500c2['time'] == t500c2['time'].max()].T
ut500c2.columns=['500']
t600c2 = c2.query('595 < time < 601')
ut600c2 = t600c2[t600c2['time'] == t600c2['time'].max()].T
ut600c2.columns=['600']
t720c2 = c2.query('715 < time < 721')
ut720c2 = t720c2[t720c2['time'] == t720c2['time'].max()].T
ut720c2.columns=['720']
t900c2 = c2.query('895 < time < 901')
ut900c2 = t900c2[t900c2['time'] == t900c2['time'].max()].T
ut900c2.columns=['900']
t1080c2 = c2.query('1075 < time < 1081')
ut1080c2 = t1080c2[t1080c2['time'] == t1080c2['time'].max()].T
ut1080c2.columns=['1080']
t1200c2 = c2.query('1195 < time < 1201')
ut1200c2 = t1200c2[t1200c2['time'] == t1200c2['time'].max()].T
ut1200c2.columns=['1200']
t1300c2 = c2.query('1295 < time < 1301')
ut1300c2 = t1300c2[t1300c2['time'] == t1300c2['time'].max()].T
ut1300c2.columns=['1300']
t1440c2 = c2.query('1435 < time < 1441')
ut1440c2 = t1440c2[t1440c2['time'] == t1440c2['time'].max()].T
ut1440c2.columns=['1440']
t1600c2 = c2.query('1595 < time < 1601')
ut1600c2 = t1600c2[t1600c2['time'] == t1600c2['time'].max()].T
ut1600c2.columns=['1600']
t1700c2 = c2.query('1695 < time < 1701')
ut1700c2 = t1700c2[t1700c2['time'] == t1700c2['time'].max()].T
ut1700c2.columns=['1700']
tminc2 = c2.query('1795 < time < 1801')
utminc2 = tminc2[tminc2['time'] == tminc2['time'].max()].T
utminc2.columns=['min']
cdsc2 = pd.concat([tnc2, umaxc2, ut100c2, ut200c2, ut360c2, ut500c2, ut600c2, ut720c2, ut900c2, ut1080c2, ut1200c2, ut1300c2,
                   ut1440c2, ut1600c2, ut1700c2, utminc2],axis = 1,join='inner')

cds = pd.concat([cdsa1, cdsa2, cdsb1, cdsb2, cdsc1, cdsc2], axis=0, join='inner')
cds.to_excel ('G:для юпитера/053.xlsx') #экспорт фрейма в excel

## ДЛЯ 1 ИЗМЕРЕНИЯ

In [ ]:
a1 = pd.read_table('G:для юпитера/060-18/a1.RV1', sep='     ', header=None)
b1 = pd.read_table('G:для юпитера/060-18/b1.RV1', sep='     ', header=None)
c1 = pd.read_table('G:для юпитера/060-18/c1.RV1', sep='     ', header=None)


a1.dropna(axis=0, inplace=True)
a1.rename(columns={0 : 'time' , 1 : 'volt'}, inplace=True)
a1['time'] = a1['time'].astype(float)
maxa1 = a1[a1['volt'] == a1['volt'].max()]
umaxa1 = maxa1[maxa1['time'] == maxa1['time'].max()].reset_index().drop(['index'], axis=1).T.reset_index().\
rename(columns={'index': 'time', 0: 'volt'}).T.rename(columns={0:'tmax', 1: 'vmax'})
tna1 = a1.loc[a1['time']<=11].max().reset_index().rename(columns={'index': 'time' , 0 : 'volt'}).\
T.rename(columns={0 : 'tn', 1 : 'vn'})
t100a1 = a1.query('95 < time < 101')
ut100a1 = t100a1[t100a1['time'] == t100a1['time'].max()].T
ut100a1.columns=['100']
t200a1 = a1.query('195 < time < 201')
ut200a1 = t200a1[t200a1['time'] == t200a1['time'].max()].T
ut200a1.columns=['200']
t360a1 = a1.query('355 < time < 361')
ut360a1 = t360a1[t360a1['time'] == t360a1['time'].max()].T
ut360a1.columns=['360']
t500a1 = a1.query('495 < time < 501')
ut500a1 = t500a1[t500a1['time'] == t500a1['time'].max()].T
ut500a1.columns=['500']
t600a1 = a1.query('595 < time < 601')
ut600a1 = t600a1[t600a1['time'] == t600a1['time'].max()].T
ut600a1.columns=['600']
t720a1 = a1.query('715 < time < 721')
ut720a1 = t720a1[t720a1['time'] == t720a1['time'].max()].T
ut720a1.columns=['720']
t900a1 = a1.query('895 < time < 901')
ut900a1 = t900a1[t900a1['time'] == t900a1['time'].max()].T
ut900a1.columns=['900']
t1080a1 = a1.query('1075 < time < 1081')
ut1080a1 = t1080a1[t1080a1['time'] == t1080a1['time'].max()].T
ut1080a1.columns=['1080']
t1200a1 = a1.query('1195 < time < 1201')
ut1200a1 = t1200a1[t1200a1['time'] == t1200a1['time'].max()].T
ut1200a1.columns=['1200']
t1300a1 = a1.query('1295 < time < 1301')
ut1300a1 = t1300a1[t1300a1['time'] == t1300a1['time'].max()].T
ut1300a1.columns=['1300']
t1440a1 = a1.query('1435 < time < 1441')
ut1440a1 = t1440a1[t1440a1['time'] == t1440a1['time'].max()].T
ut1440a1.columns=['1440']
t1600a1 = a1.query('1595 < time < 1601')
ut1600a1 = t1600a1[t1600a1['time'] == t1600a1['time'].max()].T
ut1600a1.columns=['1600']
t1700a1 = a1.query('1695 < time < 1701')
ut1700a1 = t1700a1[t1700a1['time'] == t1700a1['time'].max()].T
ut1700a1.columns=['1700']
tmina1 = a1.query('1795 < time < 1801')
utmina1 = tmina1[tmina1['time'] == tmina1['time'].max()].T
utmina1.columns=['min']
cdsa1 = pd.concat([tna1, umaxa1, ut100a1, ut200a1, ut360a1, ut500a1, ut600a1, ut720a1, ut900a1, ut1080a1, ut1200a1, ut1300a1, 
                 ut1440a1, ut1600a1, ut1700a1, utmina1],axis=1, join='inner')


b1.dropna(axis=0, inplace=True)
b1.rename(columns={0 : 'time' ,  1 : 'volt'}, inplace=True)
b1['time'] = b1['time'].astype(float)
maxb1 = b1[b1['volt'] == b1['volt'].max()]
umaxb1 = maxb1[maxb1['time'] == maxb1['time'].max()].reset_index().drop(['index'], axis=1).T.reset_index().\
rename(columns={'index': 'time', 0: 'volt'}).T.rename(columns={0:'tmax', 1: 'vmax'})
tnb1 = b1.loc[b1['time']<=11].max().reset_index().rename(columns={'index': 'time' , 0 : 'volt'}).\
T.rename(columns={0 : 'tn', 1 : 'vn'})
t100b1 = b1.query('95 < time < 101')
ut100b1 = t100b1[t100b1['time'] == t100b1['time'].max()].T
ut100b1.columns=['100']
t200b1 = b1.query('195 < time < 201')
ut200b1 = t200b1[t200b1['time'] == t200b1['time'].max()].T
ut200b1.columns=['200']
t360b1 = b1.query('355 < time < 361')
ut360b1 = t360b1[t360b1['time'] == t360b1['time'].max()].T
ut360b1.columns=['360']
t500b1 = b1.query('495 < time < 501')
ut500b1 = t500b1[t500b1['time'] == t500b1['time'].max()].T
ut500b1.columns=['500']
t600b1 = b1.query('595 < time < 601')
ut600b1 = t600b1[t600b1['time'] == t600b1['time'].max()].T
ut600b1.columns=['600']
t720b1 = b1.query('715 < time < 721')
ut720b1 = t720b1[t720b1['time'] == t720b1['time'].max()].T
ut720b1.columns=['720']
t900b1 = b1.query('895 < time < 901')
ut900b1 = t900b1[t900b1['time'] == t900b1['time'].max()].T
ut900b1.columns=['900']
t1080b1 = b1.query('1075 < time < 1081')
ut1080b1 = t1080b1[t1080b1['time'] == t1080b1['time'].max()].T
ut1080b1.columns=['1080']
t1200b1 = b1.query('1195 < time < 1201')
ut1200b1 = t1200b1[t1200b1['time'] == t1200b1['time'].max()].T
ut1200b1.columns=['1200']
t1300b1 = b1.query('1295 < time < 1301')
ut1300b1 = t1300b1[t1300b1['time'] == t1300b1['time'].max()].T
ut1300b1.columns=['1300']
t1440b1 = b1.query('1435 < time < 1441')
ut1440b1 = t1440b1[t1440b1['time'] == t1440b1['time'].max()].T
ut1440b1.columns=['1440']
t1600b1 = b1.query('1595 < time < 1601')
ut1600b1 = t1600b1[t1600b1['time'] == t1600b1['time'].max()].T
ut1600b1.columns=['1600']
t1700b1 = b1.query('1695 < time < 1701')
ut1700b1 = t1700b1[t1700b1['time'] == t1700b1['time'].max()].T
ut1700b1.columns=['1700']
tminb1 = b1.query('1795 < time < 1801')
utminb1 = tminb1[tminb1['time'] == tminb1['time'].max()].T
utminb1.columns=['min']
cdsb1 = pd.concat([tnb1, umaxb1, ut100b1, ut200b1, ut360b1, ut500b1, ut600b1, ut720b1, ut900b1, ut1080b1, ut1200b1, ut1300b1,
                   ut1440b1, ut1600b1, ut1700b1, utminb1],axis = 1,join='inner')



c1.dropna(axis=0, inplace=True)
c1.rename(columns={0 : 'time', 1 : 'volt'}, inplace=True)
c1['time'] = c1['time'].astype(float)
maxc1 = c1[c1['volt'] == c1['volt'].max()]
umaxc1 = maxc1[maxc1['time'] == maxc1['time'].max()].reset_index().drop(['index'], axis=1).T.reset_index().\
rename(columns={'index': 'time', 0: 'volt'}).T.rename(columns={0:'tmax', 1: 'vmax'})
tnc1 = c1.loc[c1['time']<=11].max().reset_index().rename(columns={'index': 'time' , 0 : 'volt'}).\
T.rename(columns={0 : 'tn', 1 : 'vn'})
t100c1 = c1.query('95 < time < 101')
ut100c1 = t100c1[t100c1['time'] == t100c1['time'].max()].T
ut100c1.columns=['100']
t200c1 = c1.query('195 < time < 201')
ut200c1 = t200c1[t200c1['time'] == t200c1['time'].max()].T
ut200c1.columns=['200']
t360c1 = c1.query('355 < time < 361')
ut360c1 = t360c1[t360c1['time'] == t360c1['time'].max()].T
ut360c1.columns=['360']
t500c1 = c1.query('495 < time < 501')
ut500c1 = t500c1[t500c1['time'] == t500c1['time'].max()].T
ut500c1.columns=['500']
t600c1 = c1.query('595 < time < 601')
ut600c1 = t600c1[t600c1['time'] == t600c1['time'].max()].T
ut600c1.columns=['600']
t720c1 = c1.query('715 < time < 721')
ut720c1 = t720c1[t720c1['time'] == t720c1['time'].max()].T
ut720c1.columns=['720']
t900c1 = c1.query('895 < time < 901')
ut900c1 = t900c1[t900c1['time'] == t900c1['time'].max()].T
ut900c1.columns=['900']
t1080c1 = c1.query('1075 < time < 1081')
ut1080c1 = t1080c1[t1080c1['time'] == t1080c1['time'].max()].T
ut1080c1.columns=['1080']
t1200c1 = c1.query('1195 < time < 1201')
ut1200c1 = t1200c1[t1200c1['time'] == t1200c1['time'].max()].T
ut1200c1.columns=['1200']
t1300c1 = c1.query('1295 < time < 1301')
ut1300c1 = t1300c1[t1300c1['time'] == t1300c1['time'].max()].T
ut1300c1.columns=['1300']
t1440c1 = c1.query('1435 < time < 1441')
ut1440c1 = t1440c1[t1440c1['time'] == t1440c1['time'].max()].T
ut1440c1.columns=['1440']
t1600c1 = c1.query('1595 < time < 1601')
ut1600c1 = t1600c1[t1600c1['time'] == t1600c1['time'].max()].T
ut1600c1.columns=['1600']
t1700c1 = c1.query('1695 < time < 1701')
ut1700c1 = t1700c1[t1700c1['time'] == t1700c1['time'].max()].T
ut1700c1.columns=['1700']
tminc1 = c1.query('1795 < time < 1801')
utminc1 = tminc1[tminc1['time'] == tminc1['time'].max()].T
utminc1.columns=['min']
cdsc1 = pd.concat([tnc1, umaxc1, ut100c1, ut200c1, ut360c1, ut500c1, ut600c1, ut720c1, ut900c1, ut1080c1, ut1200c1, ut1300c1,
                   ut1440c1, ut1600c1, ut1700c1, utminc1],axis = 1,join='inner')



cds = pd.concat([cdsa1, cdsb1, cdsc1], axis=0, join='inner')
cds.to_excel ('G:для юпитера/060-18.xlsx') #экспорт фрейма в excel

In [ ]:
#старый код
a1 = pd.read_table('G:для юпитера/051/a1.RV1', sep='     ', header=None)
a2 = pd.read_table('G:для юпитера/051/a2.RV2', sep='     ', header=None)
b1 = pd.read_table('G:для юпитера/051/b1.RV1', sep='     ', header=None)
b2 = pd.read_table('G:для юпитера/051/b2.RV2', sep='     ', header=None)
c1 = pd.read_table('G:для юпитера/051/c1.RV1', sep='     ', header=None)
c2 = pd.read_table('G:для юпитера/051/c2.RV2', sep='     ', header=None)

a1.dropna(axis=0, inplace=True)
a1.rename(columns={0 : 'time' , 1 : 'volt'}, inplace=True)
a1['time'] = a1['time'].astype(float)
maxa1 = a1[a1['volt'] == a1['volt'].max()]
umaxa1 = maxa1[maxa1['time'] == maxa1['time'].max()].T
umaxa1.columns=['tmax']
tna1 = a1.query('10 < time < 11').T 
tna1.columns=['tn']
t100a1 = a1.query('95 < time < 101')
ut100a1 = t100a1[t100a1['time'] == t100a1['time'].max()].T
ut100a1.columns=['100']
t200a1 = a1.query('195 < time < 201')
ut200a1 = t200a1[t200a1['time'] == t200a1['time'].max()].T
ut200a1.columns=['200']
t360a1 = a1.query('355 < time < 361')
ut360a1 = t360a1[t360a1['time'] == t360a1['time'].max()].T
ut360a1.columns=['360']
t500a1 = a1.query('495 < time < 501')
ut500a1 = t500a1[t500a1['time'] == t500a1['time'].max()].T
ut500a1.columns=['500']
t600a1 = a1.query('595 < time < 601')
ut600a1 = t600a1[t600a1['time'] == t600a1['time'].max()].T
ut600a1.columns=['600']
t720a1 = a1.query('715 < time < 721')
ut720a1 = t720a1[t720a1['time'] == t720a1['time'].max()].T
ut720a1.columns=['720']
t900a1 = a1.query('895 < time < 901')
ut900a1 = t900a1[t900a1['time'] == t900a1['time'].max()].T
ut900a1.columns=['900']
t1080a1 = a1.query('1075 < time < 1081')
ut1080a1 = t1080a1[t1080a1['time'] == t1080a1['time'].max()].T
ut1080a1.columns=['1080']
t1200a1 = a1.query('1195 < time < 1201')
ut1200a1 = t1200a1[t1200a1['time'] == t1200a1['time'].max()].T
ut1200a1.columns=['1200']
t1300a1 = a1.query('1295 < time < 1301')
ut1300a1 = t1300a1[t1300a1['time'] == t1300a1['time'].max()].T
ut1300a1.columns=['1300']
t1440a1 = a1.query('1435 < time < 1441')
ut1440a1 = t1440a1[t1440a1['time'] == t1440a1['time'].max()].T
ut1440a1.columns=['1440']
t1600a1 = a1.query('1595 < time < 1601')
ut1600a1 = t1600a1[t1600a1['time'] == t1600a1['time'].max()].T
ut1600a1.columns=['1600']
t1700a1 = a1.query('1695 < time < 1701')
ut1700a1 = t1700a1[t1700a1['time'] == t1700a1['time'].max()].T
ut1700a1.columns=['1700']
tmina1 = a1.query('1795 < time < 1801')
utmina1 = tmina1[tmina1['time'] == tmina1['time'].max()].T
utmina1.columns=['min']
cdsa1 = pd.concat([tna1, umaxa1, ut100a1, ut200a1, ut360a1, ut500a1, ut600a1, ut720a1, ut900a1, ut1080a1, ut1200a1, ut1300a1, 
                 ut1440a1, ut1600a1, ut1700a1, utmina1],axis=1, join='inner')

a2.dropna(axis=0, inplace=True)
a2.rename(columns={0 : 'time' ,  1 : 'volt'}, inplace=True)
a2['time'] = a2['time'].astype(float)
maxa2 = a2[a2['volt'] == a2['volt'].max()]
umaxa2 = maxa2[maxa2['time'] == maxa2['time'].max()].T
umaxa2.columns=['tmax']
tna2 = a2.query('10 < time < 11').T
tna2.columns=['tn']
t100a2 = a2.query('95 < time < 101')
ut100a2 = t100a2[t100a2['time'] == t100a2['time'].max()].T
ut100a2.columns=['100']
t200a2 = a2.query('195 < time < 201')
ut200a2 = t200a2[t200a2['time'] == t200a2['time'].max()].T
ut200a2.columns=['200']
t360a2 = a2.query('355 < time < 361')
ut360a2 = t360a2[t360a2['time'] == t360a2['time'].max()].T
ut360a2.columns=['360']
t500a2 = a2.query('495 < time < 501')
ut500a2 = t500a2[t500a2['time'] == t500a2['time'].max()].T
ut500a2.columns=['500']
t600a2 = a2.query('595 < time < 601')
ut600a2 = t600a2[t600a2['time'] == t600a2['time'].max()].T
ut600a2.columns=['600']
t720a2 = a2.query('715 < time < 721')
ut720a2 = t720a2[t720a2['time'] == t720a2['time'].max()].T
ut720a2.columns=['720']
t900a2 = a2.query('895 < time < 901')
ut900a2 = t900a2[t900a2['time'] == t900a2['time'].max()].T
ut900a2.columns=['900']
t1080a2 = a2.query('1075 < time < 1081')
ut1080a2 = t1080a2[t1080a2['time'] == t1080a2['time'].max()].T
ut1080a2.columns=['1080']
t1200a2 = a2.query('1195 < time < 1201')
ut1200a2 = t1200a2[t1200a2['time'] == t1200a2['time'].max()].T
ut1200a2.columns=['1200']
t1300a2 = a2.query('1295 < time < 1301')
ut1300a2 = t1300a2[t1300a2['time'] == t1300a2['time'].max()].T
ut1300a2.columns=['1300']
t1440a2 = a2.query('1435 < time < 1441')
ut1440a2 = t1440a2[t1440a2['time'] == t1440a2['time'].max()].T
ut1440a2.columns=['1440']
t1600a2 = a2.query('1595 < time < 1601')
ut1600a2 = t1600a2[t1600a2['time'] == t1600a2['time'].max()].T
ut1600a2.columns=['1600']
t1700a2 = a2.query('1695 < time < 1701')
ut1700a2 = t1700a2[t1700a2['time'] == t1700a2['time'].max()].T
ut1700a2.columns=['1700']
tmina2 = a2.query('1795 < time < 1801')
utmina2 = tmina2[tmina2['time'] == tmina2['time'].max()].T
utmina2.columns=['min']
cdsa2 = pd.concat([tna2, umaxa2, ut100a2, ut200a2, ut360a2, ut500a2, ut600a2, ut720a2, ut900a2, ut1080a2, ut1200a2, ut1300a2,
                   ut1440a2, ut1600a2, ut1700a2, utmina2],axis = 1,join='inner')

b1.dropna(axis=0, inplace=True)
b1.rename(columns={0 : 'time' ,  1 : 'volt'}, inplace=True)
b1['time'] = b1['time'].astype(float)
maxb1 = b1[b1['volt'] == b1['volt'].max()]
umaxb1 = maxb1[maxb1['time'] == maxb1['time'].max()].T
umaxb1.columns=['tmax']
tnb1 = b1.query('10 < time < 11').T
tnb1.columns=['tn']
t100b1 = b1.query('95 < time < 101')
ut100b1 = t100b1[t100b1['time'] == t100b1['time'].max()].T
ut100b1.columns=['100']
t200b1 = b1.query('195 < time < 201')
ut200b1 = t200b1[t200b1['time'] == t200b1['time'].max()].T
ut200b1.columns=['200']
t360b1 = b1.query('355 < time < 361')
ut360b1 = t360b1[t360b1['time'] == t360b1['time'].max()].T
ut360b1.columns=['360']
t500b1 = b1.query('495 < time < 501')
ut500b1 = t500b1[t500b1['time'] == t500b1['time'].max()].T
ut500b1.columns=['500']
t600b1 = b1.query('595 < time < 601')
ut600b1 = t600b1[t600b1['time'] == t600b1['time'].max()].T
ut600b1.columns=['600']
t720b1 = b1.query('715 < time < 721')
ut720b1 = t720b1[t720b1['time'] == t720b1['time'].max()].T
ut720b1.columns=['720']
t900b1 = b1.query('895 < time < 901')
ut900b1 = t900b1[t900b1['time'] == t900b1['time'].max()].T
ut900b1.columns=['900']
t1080b1 = b1.query('1075 < time < 1081')
ut1080b1 = t1080b1[t1080b1['time'] == t1080b1['time'].max()].T
ut1080b1.columns=['1080']
t1200b1 = b1.query('1195 < time < 1201')
ut1200b1 = t1200b1[t1200b1['time'] == t1200b1['time'].max()].T
ut1200b1.columns=['1200']
t1300b1 = b1.query('1295 < time < 1301')
ut1300b1 = t1300b1[t1300b1['time'] == t1300b1['time'].max()].T
ut1300b1.columns=['1300']
t1440b1 = b1.query('1435 < time < 1441')
ut1440b1 = t1440b1[t1440b1['time'] == t1440b1['time'].max()].T
ut1440b1.columns=['1440']
t1600b1 = b1.query('1595 < time < 1601')
ut1600b1 = t1600b1[t1600b1['time'] == t1600b1['time'].max()].T
ut1600b1.columns=['1600']
t1700b1 = b1.query('1695 < time < 1701')
ut1700b1 = t1700b1[t1700b1['time'] == t1700b1['time'].max()].T
ut1700b1.columns=['1700']
tminb1 = b1.query('1795 < time < 1801')
utminb1 = tminb1[tminb1['time'] == tminb1['time'].max()].T
utminb1.columns=['min']
cdsb1 = pd.concat([tnb1, umaxb1, ut100b1, ut200b1, ut360b1, ut500b1, ut600b1, ut720b1, ut900b1, ut1080b1, ut1200b1, ut1300b1,
                   ut1440b1, ut1600b1, ut1700b1, utminb1],axis = 1,join='inner')

b2.dropna(axis=0, inplace=True)
b2.rename(columns={0 : 'time' ,  1 : 'volt'}, inplace=True)
b2['time'] = b2['time'].astype(float)
maxb2 = b2[b2['volt'] == b2['volt'].max()]
umaxb2 = maxb2[maxb2['time'] == maxb2['time'].max()].T
umaxb2.columns=['tmax']
tnb2 = b2.query('10 < time < 11').T
tnb2.columns=['tn']
t100b2 = b2.query('95 < time < 101')
ut100b2 = t100b2[t100b2['time'] == t100b2['time'].max()].T
ut100b2.columns=['100']
t200b2 = b2.query('195 < time < 201')
ut200b2 = t200b2[t200b2['time'] == t200b2['time'].max()].T
ut200b2.columns=['200']
t360b2 = b2.query('355 < time < 361')
ut360b2 = t360b2[t360b2['time'] == t360b2['time'].max()].T
ut360b2.columns=['360']
t500b2 = b2.query('495 < time < 501')
ut500b2 = t500b2[t500b2['time'] == t500b2['time'].max()].T
ut500b2.columns=['500']
t600b2 = b2.query('595 < time < 601')
ut600b2 = t600b2[t600b2['time'] == t600b2['time'].max()].T
ut600b2.columns=['600']
t720b2 = b2.query('715 < time < 721')
ut720b2 = t720b2[t720b2['time'] == t720b2['time'].max()].T
ut720b2.columns=['720']
t900b2 = b2.query('895 < time < 901')
ut900b2 = t900b2[t900b2['time'] == t900b2['time'].max()].T
ut900b2.columns=['900']
t1080b2 = b2.query('1075 < time < 1081')
ut1080b2 = t1080b2[t1080b2['time'] == t1080b2['time'].max()].T
ut1080b2.columns=['1080']
t1200b2 = b2.query('1195 < time < 1201')
ut1200b2 = t1200b2[t1200b2['time'] == t1200b2['time'].max()].T
ut1200b2.columns=['1200']
t1300b2 = b2.query('1295 < time < 1301')
ut1300b2 = t1300b2[t1300b2['time'] == t1300b2['time'].max()].T
ut1300b2.columns=['1300']
t1440b2 = b2.query('1435 < time < 1441')
ut1440b2 = t1440b2[t1440b2['time'] == t1440b2['time'].max()].T
ut1440b2.columns=['1440']
t1600b2 = b2.query('1595 < time < 1601')
ut1600b2 = t1600b2[t1600b2['time'] == t1600b2['time'].max()].T
ut1600b2.columns=['1600']
t1700b2 = b2.query('1695 < time < 1701')
ut1700b2 = t1700b2[t1700b2['time'] == t1700b2['time'].max()].T
ut1700b2.columns=['1700']
tminb2 = b2.query('1795 < time < 1801')
utminb2 = tminb2[tminb2['time'] == tminb2['time'].max()].T
utminb2.columns=['min']
cdsb2 = pd.concat([tnb2, umaxb2, ut100b2, ut200b2, ut360b2, ut500b2, ut600b2, ut720b2, ut900b2, ut1080b2, ut1200b2, ut1300b2,
                   ut1440b2, ut1600b2, ut1700b2, utminb2],axis = 1,join='inner')

c1.dropna(axis=0, inplace=True)
c1.rename(columns={0 : 'time', 1 : 'volt'}, inplace=True)
c1['time'] = c1['time'].astype(float)
maxc1 = c1[c1['volt'] == c1['volt'].max()]
umaxc1 = maxc1[maxc1['time'] == maxc1['time'].max()].T
umaxc1.columns=['tmax']
tnc1 = c1.query('10 < time < 11').T
tnc1.columns=['tn']
t100c1 = c1.query('95 < time < 101')
ut100c1 = t100c1[t100c1['time'] == t100c1['time'].max()].T
ut100c1.columns=['100']
t200c1 = c1.query('195 < time < 201')
ut200c1 = t200c1[t200c1['time'] == t200c1['time'].max()].T
ut200c1.columns=['200']
t360c1 = c1.query('355 < time < 361')
ut360c1 = t360c1[t360c1['time'] == t360c1['time'].max()].T
ut360c1.columns=['360']
t500c1 = c1.query('495 < time < 501')
ut500c1 = t500c1[t500c1['time'] == t500c1['time'].max()].T
ut500c1.columns=['500']
t600c1 = c1.query('595 < time < 601')
ut600c1 = t600c1[t600c1['time'] == t600c1['time'].max()].T
ut600c1.columns=['600']
t720c1 = c1.query('715 < time < 721')
ut720c1 = t720c1[t720c1['time'] == t720c1['time'].max()].T
ut720c1.columns=['720']
t900c1 = c1.query('895 < time < 901')
ut900c1 = t900c1[t900c1['time'] == t900c1['time'].max()].T
ut900c1.columns=['900']
t1080c1 = c1.query('1075 < time < 1081')
ut1080c1 = t1080c1[t1080c1['time'] == t1080c1['time'].max()].T
ut1080c1.columns=['1080']
t1200c1 = c1.query('1195 < time < 1201')
ut1200c1 = t1200c1[t1200c1['time'] == t1200c1['time'].max()].T
ut1200c1.columns=['1200']
t1300c1 = c1.query('1295 < time < 1301')
ut1300c1 = t1300c1[t1300c1['time'] == t1300c1['time'].max()].T
ut1300c1.columns=['1300']
t1440c1 = c1.query('1435 < time < 1441')
ut1440c1 = t1440c1[t1440c1['time'] == t1440c1['time'].max()].T
ut1440c1.columns=['1440']
t1600c1 = c1.query('1595 < time < 1601')
ut1600c1 = t1600c1[t1600c1['time'] == t1600c1['time'].max()].T
ut1600c1.columns=['1600']
t1700c1 = c1.query('1695 < time < 1701')
ut1700c1 = t1700c1[t1700c1['time'] == t1700c1['time'].max()].T
ut1700c1.columns=['1700']
tminc1 = c1.query('1795 < time < 1801')
utminc1 = tminc1[tminc1['time'] == tminc1['time'].max()].T
utminc1.columns=['min']
cdsc1 = pd.concat([tnc1, umaxc1, ut100c1, ut200c1, ut360c1, ut500c1, ut600c1, ut720c1, ut900c1, ut1080c1, ut1200c1, ut1300c1,
                   ut1440c1, ut1600c1, ut1700c1, utminc1],axis = 1,join='inner')

c2.dropna(axis=0, inplace=True)
c2.rename(columns={0 : 'time', 1 : 'volt'}, inplace=True)
c2['time'] = c2['time'].astype(float)
maxc2 = c2[c2['volt'] == c2['volt'].max()]
umaxc2 = maxc2[maxc2['time'] == maxc2['time'].max()].T
umaxc2.columns=['tmax']
tnc2 = c2.query('10 < time < 11').T
tnc2.columns=['tn']
t100c2 = c2.query('95 < time < 101')
ut100c2 = t100c2[t100c2['time'] == t100c2['time'].max()].T
ut100c2.columns=['100']
t200c2 = c2.query('195 < time < 201')
ut200c2 = t200c2[t200c2['time'] == t200c2['time'].max()].T
ut200c2.columns=['200']
t360c2 = c2.query('355 < time < 361')
ut360c2 = t360c2[t360c2['time'] == t360c2['time'].max()].T
ut360c2.columns=['360']
t500c2 = c2.query('495 < time < 501')
ut500c2 = t500c2[t500c2['time'] == t500c2['time'].max()].T
ut500c2.columns=['500']
t600c2 = c2.query('595 < time < 601')
ut600c2 = t600c2[t600c2['time'] == t600c2['time'].max()].T
ut600c2.columns=['600']
t720c2 = c2.query('715 < time < 721')
ut720c2 = t720c2[t720c2['time'] == t720c2['time'].max()].T
ut720c2.columns=['720']
t900c2 = c2.query('895 < time < 901')
ut900c2 = t900c2[t900c2['time'] == t900c2['time'].max()].T
ut900c2.columns=['900']
t1080c2 = c2.query('1075 < time < 1081')
ut1080c2 = t1080c2[t1080c2['time'] == t1080c2['time'].max()].T
ut1080c2.columns=['1080']
t1200c2 = c2.query('1195 < time < 1201')
ut1200c2 = t1200c2[t1200c2['time'] == t1200c2['time'].max()].T
ut1200c2.columns=['1200']
t1300c2 = c2.query('1295 < time < 1301')
ut1300c2 = t1300c2[t1300c2['time'] == t1300c2['time'].max()].T
ut1300c2.columns=['1300']
t1440c2 = c2.query('1435 < time < 1441')
ut1440c2 = t1440c2[t1440c2['time'] == t1440c2['time'].max()].T
ut1440c2.columns=['1440']
t1600c2 = c2.query('1595 < time < 1601')
ut1600c2 = t1600c2[t1600c2['time'] == t1600c2['time'].max()].T
ut1600c2.columns=['1600']
t1700c2 = c2.query('1695 < time < 1701')
ut1700c2 = t1700c2[t1700c2['time'] == t1700c2['time'].max()].T
ut1700c2.columns=['1700']
tminc2 = c2.query('1795 < time < 1801')
utminc2 = tminc2[tminc2['time'] == tminc2['time'].max()].T
utminc2.columns=['min']
cdsc2 = pd.concat([tnc2, umaxc2, ut100c2, ut200c2, ut360c2, ut500c2, ut600c2, ut720c2, ut900c2, ut1080c2, ut1200c2, ut1300c2,
                   ut1440c2, ut1600c2, ut1700c2, utminc2],axis = 1,join='inner')

cds = pd.concat([cdsa1, cdsa2, cdsb1, cdsb2, cdsc1, cdsc2], axis=0, join='inner')
#cds.to_excel ('G:для юпитера/cds050.xlsx') #экспорт фрейма в excel

## доработка кода

In [ ]:
a1 = pd.read_table('G:для юпитера/060-18/a1.RV1', sep='     ', header=None)

a1.dropna(axis=0, inplace=True)
a1.rename(columns={0 : 'time' , 1 : 'volt'}, inplace=True)
a1['time'] = a1['time'].astype(float)

In [ ]:
tna1 = a1.loc[a1['time']<=11].max().reset_index().rename(columns={'index': 'time' , 0 : 'volt'}).\
T.rename(columns={0 : 'tn', 1 : 'vn'})
#valid code

In [ ]:
#umaxa1 = 
maxa1 = a1[a1['volt'] == a1['volt'].max()]
umaxa1 = maxa1[maxa1['time'] == maxa1['time'].max()].reset_index().drop(['index'], axis=1).T.reset_index().\
rename(columns={'index': 'time', 0: 'volt'}).T.rename(columns={0:'tmax', 1: 'vmax'})
#valid code

In [ ]:
ut100a1 = a1.loc[a1['time']<=101].max().to_frame().rename(columns={0 : 100})
#valid code
#t100a1 = a1.query('95 < time < 101')
#xt100a1 = t100a1[t100a1['time'] == t100a1['time'].max()].T
#xt100a1.columns=['100']